include:
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view_gem
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view_gem
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
