include:
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: sofle_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset
